import { CardProps } from "@/components/Team/TeamCard/TeamCard";

export const TeamMembers: CardProps[] = [
  {
    name: "Chiku Okechukwu",
    initials: "CO",
    image: "chikuokechukwu.webp",
    role: "Director",
    linkedinUrl: "https://www.linkedin.com/in/chiku-okechukwu-19942523b/",
  },
  {
    name: "Egi Rama",
    initials: "ER",
    image: "egirama.webp",
    role: "Director",
    linkedinUrl: "https://www.linkedin.com/in/egi-rama-094a531b9/",
  },
  {
    name: "Christine Kapp",
    initials: "CK",
    image: "christinekapp.webp",
    role: "Director",
    linkedinUrl: "https://www.linkedin.com/in/christine-kapp-658b41238",
  },
  {
    name: "Stephen MacNeil",
    initials: "SM",
    image: "stephenmacneil.webp",
    role: "Faculty Advisor",
    linkedinUrl: "https://www.linkedin.com/in/stevemacn1/",
  },
  {
    name: "Andrew Tran",
    initials: "AT",
    image: "andrewtran.webp",
    role: "Sponsorship",
    linkedinUrl: "https://www.linkedin.com/in/andrewtran117/",
    githubUrl: "https://github.com/adrewtran117",
  },
  {
    name: "Devin Rankin",
    initials: "DR",
    image: "devinrankin.webp",
    role: "Web Development",
    linkedinUrl: "https://www.linkedin.com/in/devin-rankin-div/",
    githubUrl: "https://github.com/devinrankin",
    websiteUrl: "https://devinrank.in",
  },
  {
    name: "Phuykong Meng",
    initials: "PM",
    image: "mengphuykong.webp",
    role: "Web Development",
    linkedinUrl: "https://www.linkedin.com/in/phuykong-meng/",
    githubUrl: "https://github.com/M-Phuykong",
  },
  {
    name: "Adyan Chowdhury",
    initials: "AC",
    image: "adyanchowdhury.webp",
    role: "Logistics",
    linkedinUrl: "https://www.linkedin.com/in/adyan-chowdhury/",
    githubUrl: "https://github.com/adyan1025",
  },
  {
    name: "Chyanne Polycarpe",
    initials: "CP",
    image: "chyannepolycarpe.webp",
    role: "Logistics",
    linkedinUrl: "https://www.linkedin.com/in/chyanne-polycarpe/",
  },
  {
    name: "Hena Patel",
    initials: "HP",
    image: "henapatel.webp",
    role: "Logistics",
    linkedinUrl: "https://www.linkedin.com/in/henapatel3124/",
  },
  {
    name: "Kriti Baru",
    initials: "KB",
    image: "kritibaru.webp",
    role: "Operations",
    linkedinUrl: "https://www.linkedin.com/in/kriti-baru/",
  },
  {
    name: "Kush Patel",
    initials: "KP",
    image: "kushpatel.webp",
    role: "Sponsorship",
    linkedinUrl: "https://www.linkedin.com/in/kushpatel00/",
  },
  {
    name: "Megha Joshi",
    initials: "MJ",
    image: "meghajoshi.webp",
    role: "Operations",
    linkedinUrl: "http://linkedin.com/in/megha-joshi-578609250",
  },
  {
    name: "Oswayne Smith",
    initials: "OS",
    image: "oswaynesmith.webp",
    role: "Logistics",
    linkedinUrl: "https://www.linkedin.com/in/oswayne-smith-628b29265/",
  },
  {
    name: "Shrey Patel",
    initials: "SP",
    image: "shreypatel.webp",
    role: "Operations",
    linkedinUrl: "https://www.linkedin.com/in/shr3y",
  },
  {
    name: "Sophie Metille",
    initials: "SM",
    image: "sophiemetille.webp",
    role: "Design",
    linkedinUrl: "https://www.linkedin.com/in/sophia-mettille-b56329256/",
  },
  {
    name: "Susan Daniel",
    initials: "SD",
    image: "susandaniel.webp",
    role: "Sponsorship",
    linkedinUrl: "https://www.linkedin.com/in/susan-daniel-354532220/",
  },
  {
    name: "Timilehin Olofinyolemi",
    initials: "TO",
    image: "timilehinolofinyolemi.webp",
    role: "Operations",
    linkedinUrl: "https://www.linkedin.com/in/timiolofin/",
  },
  {
    name: "Trevor Flick",
    initials: "TF",
    image: "trevorflick.webp",
    role: "Design",
    linkedinUrl: "https://www.linkedin.com/in/trevor-flick/",
  },
  {
    name: "Yatri Patel",
    initials: "YP",
    image: "yatripatel.webp",
    role: "Sponsorship",
    linkedinUrl: "https://www.linkedin.com/in/yatri-patel-229710291/",
  },

  {
    name: "Noel Chacko",
    initials: "NC",
    image: "noelchacko.webp",
    role: "Design",
    linkedinUrl: "https://www.linkedin.com/in/noel-chacko/",
  },
  {
    name: "Daniel Bicalho",
    initials: "DB",
    image: "danielbicalho.webp",
    role: "Sponsorship",
    linkedinUrl: "https://www.linkedin.com/in/danielsbicalho/",
  },
  {
    name: "Julia Conigliari",
    initials: "JC",
    image: "juliaconigliari.webp",
    role: "Design",
    linkedinUrl: "https://www.linkedin.com/in/julia-conigliari/",
  },

  {
    name: "Ryan Stanton",
    initials: "RS",
    image: "ryanstanton.webp",
    role: "Operations",
    linkedinUrl: "https://www.linkedin.com/in/ryan-stanton-8b3850221/",
  },
  {
    name: "Sophie Chen",
    initials: "SC",
    image: "sophiechen.webp",
    role: "Sponsorship",
    linkedinUrl: "https://linkedin.com/in/sophiechen7/",
  },
  {
    name: "Seth Bernstein",
    initials: "SB",
    image: "sethbernstein.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/seth-bernstein-b23a36200/",
    githubUrl: "",
  },
  {
    name: "Kenneth Angelikas",
    initials: "KA",
    image: "kennethangelikas.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/kenneth-angelikas/",
  },
  {
    name: "Yashi Patel",
    initials: "YP",
    image: "yashipatel.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/yashi-patel1027/",
    githubUrl: "https://github.com/yashipat",
  },
];
