import type { EndorserProps } from "@/components/HomePage/Endorsements/Endorser";

export const NonProfit: EndorserProps[] = [
  {
    src: "/endorsement_logo/ezcater.svg",
    href: "",
    ariaLabel: "ezCater",
    altText: "ezCater",
    width: 100,
    height: 100,
  },
  {
    src: "/endorsement_logo/saxbys.svg",
    href: "",
    ariaLabel: "Saxbys",
    altText: "Saxbys",
    width: 100,
    height: 100,
  },
  {
    src: "/endorsement_logo/chipotle.svg",
    href: "",
    ariaLabel: "Chipotle",
    altText: "Chipotle",
    width: 100,
    height: 100,
  },
  {
    src: "/endorsement_logo/celsius.svg",
    href: "",
    ariaLabel: "Celcius",
    altText: "Celcius",
    width: 100,
    height: 100,
  },
  {
    src: "/endorsement_logo/redbull.svg",
    href: "",
    ariaLabel: "Red Bull",
    altText: "Red Bull",
    width: 100,
    height: 100,
  },
  {
    src: "/endorsement_logo/monsterenergy.svg",
    href: "",
    ariaLabel: "Monster Energy",
    altText: "Monster Energy",
    width: 100,
    height: 100,
  },
  {
    src: "/endorsement_logo/poppi.svg",
    href: "",
    ariaLabel: "Drink Poppi",
    altText: "Drink Poppi",
    width: 100,
    height: 100,
  },
  {
    src: "/endorsement_logo/nordvpn.png",
    href: "https://nordvpn.com/hackathons",
    ariaLabel: "NordVPN",
    altText: "NordVPN",
    width: 120,
    height: 56,
    rel: "noopener noreferrer nofollow sponsored",
  },
  {
    src: "/endorsement_logo/incogni.png",
    href: "https://incogni.com/",
    ariaLabel: "Incogni",
    altText: "Incogni",
    width: 120,
    height: 55,
    rel: "noopener noreferrer nofollow sponsored",
  },
  {
    src: "/endorsement_logo/nordpass.png",
    href: "https://nordpass.com/",
    ariaLabel: "NordPass",
    altText: "NordPass",
    width: 100,
    height: 91,
    rel: "noopener noreferrer nofollow sponsored",
  },
  {
    src: "/endorsement_logo/saily.png",
    href: "https://saily.com/",
    ariaLabel: "Saily",
    altText: "Saily",
    width: 115,
    height: 71,
    rel: "noopener noreferrer nofollow sponsored",
  },
  {
    src: "/endorsement_logo/coveron.png",
    href: "https://coveron.com/",
    ariaLabel: "Coveron",
    altText: "Coveron",
    width: 100,
    height: 100,
    rel: "noopener noreferrer nofollow sponsored",
  },
];
