import type { EndorserProps } from "@/components/HomePage/Endorsements/Endorser";

export const NonProfit: EndorserProps[] = [
  {
    src: "/endorsement_logo/ezcater.svg",
    href: "",
    ariaLabel: "ezCater",
    altText: "ezCater",
    width: 100,
    height: 100,
  },
  {
    src: "/endorsement_logo/saxbys.svg",
    href: "",
    ariaLabel: "Saxbys",
    altText: "Saxbys",
    width: 100,
    height: 100,
  },
  {
    src: "/endorsement_logo/chipotle.svg",
    href: "",
    ariaLabel: "Chipotle",
    altText: "Chipotle",
    width: 100,
    height: 100,
  },
  {
    src: "/endorsement_logo/celsius.svg",
    href: "",
    ariaLabel: "Celcius",
    altText: "Celcius",
    width: 100,
    height: 100,
  },
  {
    src: "/endorsement_logo/redbull.svg",
    href: "",
    ariaLabel: "Red Bull",
    altText: "Red Bull",
    width: 100,
    height: 100,
  },
  {
    src: "/endorsement_logo/monsterenergy.svg",
    href: "",
    ariaLabel: "Monster Energy",
    altText: "Monster Energy",
    width: 100,
    height: 100,
  },
  {
    src: "/endorsement_logo/poppi.svg",
    href: "",
    ariaLabel: "Drink Poppi",
    altText: "Drink Poppi",
    width: 100,
    height: 100,
  },
];
