import { CardProps } from "@/components/HomePage/Team/TeamCard/TeamCard";

export const TeamMembers: CardProps[] = [
  {
    name: "Christine Kapp",
    initials: "CK",
    image: "christinekapp.webp",
    role: "Director",
    linkedinUrl: "https://www.linkedin.com/in/christine-kapp-658b41238",
  },
  {
    name: "Shrey Patel",
    initials: "SP",
    image: "shreypatel.webp",
    role: "Director",
    linkedinUrl: "https://www.linkedin.com/in/shr3y",
  },
  {
    name: "Kush Patel",
    initials: "KP",
    image: "kushpatel.webp",
    role: "Director",
    linkedinUrl: "https://www.linkedin.com/in/kushpatel00/",
  },
  {
    name: "Yatri Patel",
    initials: "YP",
    image: "yatripatel.webp",
    role: "Director",
    linkedinUrl: "https://www.linkedin.com/in/yatri-patel-229710291/",
  },
  {
    name: "Devin Rankin",
    initials: "DR",
    image: "devinrankin.webp",
    role: "Web Development",
    linkedinUrl: "https://www.linkedin.com/in/devin-rankin-div/",
    githubUrl: "https://github.com/devinrankin",
    websiteUrl: "https://devinrank.in",
  },
  {
    name: "Phuykong Meng",
    initials: "PM",
    image: "mengphuykong.webp",
    role: "Web Development",
    linkedinUrl: "https://www.linkedin.com/in/phuykong-meng/",
    githubUrl: "https://github.com/M-Phuykong",
    websiteUrl: "https://mphuykong.dev/",
  },
  {
    name: "Adyan Chowdhury",
    initials: "AC",
    image: "adyanchowdhury.webp",
    role: "Logistics",
    linkedinUrl: "https://www.linkedin.com/in/adyan-chowdhury/",
    githubUrl: "https://github.com/adyan1025",
  },
  {
    name: "Nene Coulibaly",
    initials: "NC",
    image: "empty.webp",
    role: "Logistics",
    linkedinUrl: "",
  },
  {
    name: "Antonio Lazaro",
    initials: "AL",
    image: "antoniolazaro.webp",
    role: "Logistics",
    linkedinUrl: "https://www.linkedin.com/in/antonio-lazaro-13848b308/",
  },
  // {
  //   name: "Morgan Butler",
  //   initials: "MB",
  //   image: "empty.webp",
  //   role: "Logistics",
  //   linkedinUrl: "",
  // },
  // {
  //   name: "Zack Aidarov",
  //   initials: "ZA",
  //   image: "empty.webp",
  //   role: "Logistics",
  //   linkedinUrl: "",
  // },
  {
    name: "John Kroll",
    initials: "JK",
    image: "gregkroll.webp",
    role: "Logistics",
    linkedinUrl: "https://www.linkedin.com/in/johnkroll22/",
  },
  // {
  //   name: "Elijah Hubbard",
  //   initials: "EH",
  //   image: "empty.webp",
  //   role: "Logistics",
  //   linkedinUrl: "",
  // },
  {
    name: "Kriti Baru",
    initials: "KB",
    image: "kritibaru.webp",
    role: "Operations",
    linkedinUrl: "https://www.linkedin.com/in/kriti-baru/",
  },
  {
    name: "Megha Joshi",
    initials: "MJ",
    image: "meghajoshi.webp",
    role: "Operations",
    linkedinUrl: "http://linkedin.com/in/megha-joshi-578609250",
  },
  {
    name: "Timilehin Olofinyolemi",
    initials: "TO",
    image: "timilehinolofinyolemi.webp",
    role: "Operations",
    linkedinUrl: "https://www.linkedin.com/in/timiolofin/",
  },
  {
    name: "Sheena Nnam",
    initials: "SN",
    image: "sheenannam.webp",
    role: "Operations",
    linkedinUrl: "https://www.linkedin.com/in/snnam/",
  },
  {
    name: "Lydon Gavin",
    initials: "LG",
    image: "lydongavin.webp",
    role: "Operations",
    linkedinUrl: "https://www.linkedin.com/in/lydon-gavin/",
  },
  {
    name: "Victor Awoleye",
    initials: "VA",
    image: "empty.webp",
    role: "Operations",
    linkedinUrl: "",
  },
  {
    name: "Maahin Mirza",
    initials: "MM",
    image: "maahinmirza.webp",
    role: "Operations",
    linkedinUrl: "https://www.linkedin.com/in/maahinmirza/",
  },
  // {
  //   name: "Hyunsoo Jin",
  //   initials: "HJ",
  //   image: "empty.webp",
  //   role: "Operations",
  //   linkedinUrl: "",
  // },
  {
    name: "Oswayne Smith",
    initials: "OS",
    image: "oswaynesmith.webp",
    role: "Design",
    linkedinUrl: "https://www.linkedin.com/in/oswayne-smith-628b29265/",
  },
  {
    name: "Nana Korsah",
    initials: "NK",
    image: "empty.webp",
    role: "Design",
    linkedinUrl: "",
  },
  {
    name: "Nandita Reddy",
    initials: "NR",
    image: "nanditareddy.webp",
    role: "Design",
    linkedinUrl: "https://www.linkedin.com/in/nandita-reddy/",
  },
  {
    name: "Billy Phan",
    initials: "BP",
    image: "billyphan.webp",
    role: "Design",
    linkedinUrl: "https://www.linkedin.com/in/billyphann/",
  },
  // {
  //   name: "Angel Chason",
  //   initials: "AC",
  //   image: "empty.webp",
  //   role: "Design",
  //   linkedinUrl: "",
  // },
  {
    name: "Rapheal Ankrah",
    initials: "RA",
    image: "empty.webp",
    role: "Design",
    linkedinUrl: "",
  },
  // {
  //   name: "Eric Eleam",
  //   initials: "EE",
  //   image: "empty.webp",
  //   role: "Design",
  //   linkedinUrl: "",
  // },
  {
    name: "Sara Fuertes",
    initials: "SF",
    image: "empty.webp",
    role: "Design",
    linkedinUrl: "",
  },
  // {
  //   name: "Manifest(Eric) Akosah Jr.",
  //   initials: "MA",
  //   image: "empty.webp",
  //   role: "Design",
  //   linkedinUrl: "",
  // },
  {
    name: "Daniel Bicalho",
    initials: "DB",
    image: "danielbicalho.webp",
    role: "Sponsorship",
    linkedinUrl: "https://www.linkedin.com/in/danielsbicalho/",
  },
  {
    name: "Yashi Patel",
    initials: "YP",
    image: "yashipatel.webp",
    role: "Sponsorship",
    linkedinUrl: "https://www.linkedin.com/in/yashi-patel1027/",
    githubUrl: "https://github.com/yashipat",
  },
  // {
  //   name: "Silas Carvalho",
  //   initials: "SC",
  //   image: "empty.webp",
  //   role: "Sponsorship",
  //   linkedinUrl: ""
  // },
  {
    name: "Ashfin Rahman",
    initials: "AR",
    image: "empty.webp",
    role: "Sponsorship",
    linkedinUrl: ""
  },
  {
    name: "Lavdrim Islami",
    initials: "LI",
    image: "lavdrimislami.webp",
    role: "Sponsorship",
    linkedinUrl: "https://www.linkedin.com/in/lavdrimislami/"
  },
  {
    name: "Dev Patel",
    initials: "DP",
    image: "devpatel.webp",
    role: "Sponsorship",
    linkedinUrl: "https://www.linkedin.com/in/dev-patelll/"
  },
  {
    name: "Chandrahas Rachamadugu",
    initials: "CR",
    image: "chandrahas.webp",
    role: "Sponsorship",
    linkedinUrl: "https://www.linkedin.com/in/chandrahas-rachamadugu/"
  },
  {
    name: "Michael Zach",
    initials: "MZ",
    image: "empty.webp",
    role: "Sponsorship",
    linkedinUrl: ""
  },
  // {
  //   name: "Gino Russo",
  //   initials: "GR",
  //   image: "empty.webp",
  //   role: "Sponsorship",
  //   linkedinUrl: ""
  // },
  {
    name: "Mit Patel",
    initials: "MPP",
    image: "mitpatel.webp",
    role: "Sponsorship",
    linkedinUrl: "https://www.linkedin.com/in/mit-patel-a176a6226/"
  },
  {
    name: "Meet Patel",
    initials: "MP",
    image: "meetpatel.webp",
    role: "Sponsorship",
    linkedinUrl: ""
  },
  // },
  // {
  //   name: "Kenneth Angelikas",
  //   initials: "KA",
  //   image: "kennethangelikas.webp",
  //   role: "Outreach",
  //   linkedinUrl: "https://www.linkedin.com/in/kenneth-angelikas/",
  // },
  {
    name: "Srishty Muthusekaran",
    initials: "SM",
    image: "srishtymuthusekaran.webp",
    role: "Outreach",
    linkedinUrl: "https://www.linkedin.com/in/srishty-m/",
  },
  // {
  //   name: "Tyree Milord",
  //   initials: "TM",
  //   image: "empty.webp",
  //   role: "Outreach",
  //   linkedinUrl: "",
  // },
  {
    name: "Fatoumata Jalloh",
    initials: "FJ",
    image: "fatoumatajalloh.webp",
    role: "Outreach",
    linkedinUrl: "https://www.linkedin.com/in/fatoumataj/",
  },
  {
    name: "Jenni Sorathiya",
    initials: "JS",
    image: "jenisorathiya.webp",
    role: "Outreach",
    linkedinUrl: "https://www.linkedin.com/in/jeni-sorathiya/",
  },
  {
    name: "Huyen La",
    initials: "HL",
    image: "huyenla.webp",
    role: "Outreach",
    linkedinUrl: "https://www.linkedin.com/in/huyen-la-74063125a/",
  },
  // {
  //   name: "Saumika Pandey",
  //   initials: "SP",
  //   image: "empty.webp",
  //   role: "Outreach",
  //   linkedinUrl: "",
  // },
  {
    name: "Yesha Shah",
    initials: "SM",
    image: "yeshashah.webp",
    role: "Outreach",
    linkedinUrl: "https://www.linkedin.com/in/yesha-shah0021/",
  },

  {
    name: "Rayhona Nasimova ",
    initials: "RN",
    image: "rayhonanasimova.webp",
    role: "DEI",
    linkedinUrl: "https://www.linkedin.com/in/rayhona-nasimova/",
  }
  // },

  // {
  //   name: "Manya Khullar",
  //   initials: "MK",
  //   image: "empty.webp",
  //   role: "DEI",
  //   linkedinUrl: "",
  // },

];
