import { MemberProps } from "../_components/Team/TeamMember/Member";

export const TeamMembers: MemberProps[] = [
  {
    name: "Chiku Okechukwu",
    initials: "CO",
    image: "chikuokechukwu.webp",
    role: "Director",
    linkedinUrl: "https://www.linkedin.com/in/chiku-okechukwu-19942523b/",
  },
  {
    name: "Seth Bernstein",
    initials: "SB",
    image: "sethbernstein.webp",
    role: "Director",
    linkedinUrl: "https://www.linkedin.com/in/seth-bernstein-b23a36200/",
    githubUrl: ""
  },
  {
    name: "Andrew Tran",
    initials: "AT",
    image: "andrewtran.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/andrewtran117/",
    githubUrl: "https://github.com/adrewtran117",
  },
  {
    name: "Noel Chacko",
    initials: "NC",
    image: "noelchacko.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/noel-chacko/",
  },
  {
    name: "Egi Rama",
    initials: "ER",
    image: "egirama.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/egi-rama-094a531b9/",
  },
  {
    name: "Phuykong Meng",
    initials: "PM",
    image: "mengphuykong.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/phuykong-meng/",
    githubUrl: "https://github.com/M-Phuykong"
  },
  {
    name: "Adyan Chowdhury",
    initials: "AC",
    image: "adyanchowdhury.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/adyan-chowdhury/",
    githubUrl: "https://github.com/adyan1025"
  },
  {
    name: "Christine Kapp",
    initials: "CK",
    image: "christinekapp.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/christine-kapp-658b41238",
  },
  {
    name: "Chyanne Polycarpe",
    initials: "CP",
    image: "chyannepolycarpe.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/chyanne-polycarpe/",
  },
  {
    name: "Daniel Bicahlo",
    initials: "DB",
    image: "danielbicahlo.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/danielsbicalho/",
  },
  {
    name: "Emmanuel Ortiz",
    initials: "EO",
    image: "emmanuelortiz.webp",
    role: "",
    linkedinUrl: "",
  },
  {
    name: "Hena Patel",
    initials: "HP",
    image: "henapatel.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/henapatel3124/",
  },
  {
    name: "Jihye Lee",
    initials: "JL",
    image: "jihyelee.webp",
    role: "",
    linkedinUrl: "",
  },
  {
    name: "Julia Conigliari",
    initials: "JC",
    image: "juliaconigliari.webp",
    role: "",
    linkedinUrl: "",
  },
  {
    name: "Kenneth Angelikas",
    initials: "KA",
    image: "kennethangelikas.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/kenneth-angelikas/",
  },
  {
    name: "Kriti Baru",
    initials: "KB",
    image: "kritibaru.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/kriti-baru/",
  },
  {
    name: "Kush Patel",
    initials: "KP",
    image: "kushpatel.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/kushpatel00/",
  },
  {
    name: "Magdalena Rogalska",
    initials: "MR",
    image: "magdalenarogalska.webp",
    role: "",
    linkedinUrl: "",
  },
  {
    name: "Megha Joshi",
    initials: "MJ",
    image: "meghajoshi.webp",
    role: "",
    linkedinUrl: "http://linkedin.com/in/megha-joshi-578609250",
  },
  {
    name: "Oscar Levin",
    initials: "OL",
    image: "oscarlevin.webp",
    role: "",
    linkedinUrl: "",
  },
  {
    name: "Owswayne Smith",
    initials: "OS",
    image: "owswaynesmith.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/oswayne-smith-628b29265/",
  },
  {
    name: "Ryan Stanton",
    initials: "RS",
    image: "ryanstanton.webp",
    role: "",
    linkedinUrl: "",
  },
  {
    name: "Shrey Patel",
    initials: "SP",
    image: "shreypatel.webp",
    role: "",
    linkedinUrl: "www.linkedin.com/in/sshr3yy",
  },
  {
    name: "Sophie Chen",
    initials: "SC",
    image: "sophiechen.webp",
    role: "",
    linkedinUrl: "https://linkedin.com/in/sophiechen7/",
  },
  {
    name: "Sophie Metille",
    initials: "SM",
    image: "sophiemetille.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/sophia-mettille-b56329256/",
  },
  {
    name: "Stephen MacNeil",
    initials: "SM",
    image: "stephenmacneil.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/stevemacn1/",
  },
  {
    name: "Susan Daniel",
    initials: "SD",
    image: "susandaniel.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/susan-daniel-354532220/",
  },
  {
    name: "Timilehin Olofinyolemi",
    initials: "TO",
    image: "timilehinolofinyolemi.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/timiolofin/",
  },
  {
    name: "Trevor Flick",
    initials: "TF",
    image: "trevorflick.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/trevor-flick/",
  },
  {
    name: "Yatri Patel",
    initials: "YP",
    image: "yatripatel.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/yatri-patel-229710291/",
  },
  {
    name: "Yashi Patel",
    initials: "YP",
    image: "yashipatel.webp",
    role: "",
    linkedinUrl: "https://www.linkedin.com/in/yashi-patel1027/",
  }
];
